import os
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import streamlit as st
from typing import Optional, Dict, Any
import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime
import os

from utils.unified_predictor import predict as unified_predict
from utils.gemini_helper import get_support_response
from utils.history_logger import log_entry, load_history, load_history_dataframe
from utils.config import LABELS, DATA_DIR


def _load_evaluation_comparison():
    """Load model comparison artifacts generated by training/evaluate_models.py."""
    import json as _json
    from pathlib import Path

    results_dir = Path(__file__).resolve().parent / "results"
    candidate_csvs = [results_dir / "compare_models.csv", results_dir / "model_comparison.csv"]
    candidate_jsons = [results_dir / "compare_models.json", results_dir / "model_comparison.json"]

    out = {"compare_df": None, "compare_json": None, "artifacts_present": False}
    for csv_path in candidate_csvs:
        if csv_path.exists():
            try:
                out["compare_df"] = pd.read_csv(csv_path)
                break
            except Exception:
                out["compare_df"] = None

    for json_path in candidate_jsons:
        if json_path.exists():
            try:
                out["compare_json"] = _json.loads(json_path.read_text(encoding="utf-8"))
                break
            except Exception:
                out["compare_json"] = None

    if out["compare_df"] is not None:
        expected_cols = {"model", "accuracy", "precision", "recall", "f1"}
        missing = expected_cols.difference(set(out["compare_df"].columns))
        if missing:
            out["compare_df"] = None

    out["artifacts_present"] = (out["compare_df"] is not None) or (out["compare_json"] is not None)
    out["results_dir"] = str(results_dir)
    out["cm_bilstm_path"] = str(results_dir / "confusion_matrix_bilstm.png")
    out["cm_bert_path"] = str(results_dir / "confusion_matrix_bert.png")
    return out


from utils.logger import get_logger

logger = get_logger(__name__)


st.set_page_config(page_title="Student Emotion Support", layout="wide")


def _apply_theme(dark: bool) -> None:
    """Apply minimal theme adjustments via CSS for a polished look."""
    if dark:
        st.markdown(
            """
            <style>
            .stApp { background-color: #0e1117; color: #e6eef8 }
            .card { background: #11121a; padding:16px; border-radius:8px; }
            .muted { color: #9aa7bf }
            </style>
            """,
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            """
            <style>
            .card { background: #ffffff; padding:16px; border-radius:8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
            .muted { color: #6b7280 }
            </style>
            """,
            unsafe_allow_html=True,
        )


def cached_predict(text: str, model_choice: str) -> Optional[Dict[str, Any]]:
    """Wrapper around `unified_predict` with simple caching via session_state.

    We avoid heavy st.cache_data here because the underlying models may be
    large and already cached by their own loaders.
    """
    key = f"pred:{model_choice}:{hash(text)}"
    if key in st.session_state:
        return st.session_state[key]
    try:
        res = unified_predict(text, model_choice=model_choice)
        st.session_state[key] = res
        return res
    except Exception as e:
        st.error(f"Prediction failed: {e}")
        logger.exception("Prediction failed for text: %s", text)
        return None


def _normalize_probs_for_display(prob_values: Any) -> list[float]:
    if prob_values is None:
        return [0.0] * len(LABELS)

    arr = np.asarray(prob_values, dtype=float).reshape(-1)
    if arr.size == 0:
        return [0.0] * len(LABELS)
    if arr.size < len(LABELS):
        padded = np.zeros(len(LABELS), dtype=float)
        padded[: arr.size] = arr
        arr = padded
    elif arr.size > len(LABELS):
        arr = arr[: len(LABELS)]

    arr = np.clip(arr, 0.0, None)
    arr = np.nan_to_num(arr, nan=0.0, posinf=0.0, neginf=0.0)
    total = float(arr.sum())
    if not np.isfinite(total) or total <= 0:
        return [1.0 / len(LABELS)] * len(LABELS)
    return (arr / total).tolist()


def download_dataframe_as_csv(df: pd.DataFrame, filename: str = "history.csv"):
    return df.to_csv(index=False).encode("utf-8")


def clear_history_file() -> None:
    path = DATA_DIR / "history.csv"
    if path.exists():
        path.unlink()


_sidebar = st.sidebar
_sidebar.title("Controls")

model_choice = _sidebar.selectbox("Model", options=["Both", "BERT", "BiLSTM"], index=0)
theme = _sidebar.radio("Theme", options=["Light", "Dark"], index=0)
_apply_theme(theme == "Dark")

st.title("Student Emotion Support — Live Analyzer")

with st.container():
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("Student Message")
        text = st.text_area("Paste student text here", height=160)
        if not text:
            st.info("Enter a message above to analyze emotions and get guidance.")

        submit = st.button("Analyze")

    with col2:
        st.subheader("Quick Actions")
        if st.button("Clear history"):
            clear_history_file()
            st.success("History cleared.")
        rows = load_history()
        st.caption(f"History rows: {len(rows)}")

    if submit:
        if not text.strip():
            st.error("Please enter some text to analyze.")
        else:
            with st.spinner("Analyzing message..."):
                result = cached_predict(text, model_choice)

            if result is None:
                st.error("No prediction available.")
            else:
                # Save to history
                try:
                    log_entry(text, result.get("bilstm_pred"), result.get("bert_pred"), result.get("final_prediction"), result.get("confidence"))
                except Exception:
                    st.warning("Failed to write history; continuing without saving.")

                # Layout for prediction card + model bars
                pcol1, pcol2 = st.columns([2, 3])

                with pcol1:
                    st.markdown("## Prediction")
                    st.markdown(f"**Final:** {result.get('final_prediction')} \n\n**Confidence:** {result.get('confidence'):.2f}" if result.get('confidence') is not None else "No confidence")

                    mixed = result.get("mixed", {})
                    if mixed.get("mixed"):
                        st.markdown("**Mixed emotions detected**")
                        st.markdown(f"Primary: {mixed.get('primary')} ({mixed.get('primary_prob'):.2f})\n\nSecondary: {mixed.get('secondary')} ({mixed.get('secondary_prob'):.2f})")

                    # Gemini guidance
                    regen_key = f"regen:{hash(text)}"
                    if regen_key not in st.session_state:
                        st.session_state[regen_key] = None

                    if st.session_state[regen_key] is None:
                        with st.spinner("Generating supportive guidance..."):
                            advice = get_support_response(result.get("final_prediction"), mixed.get("secondary"), result.get("confidence"), text, field="education")
                            st.session_state[regen_key] = advice
                    st.markdown("### Guidance")
                    st.write(st.session_state[regen_key])
                    if st.button("Regenerate guidance"):
                        with st.spinner("Regenerating guidance..."):
                            advice = get_support_response(result.get("final_prediction"), mixed.get("secondary"), result.get("confidence"), text, field="education")
                            st.session_state[regen_key] = advice
                            st.rerun()

                with pcol2:
                    st.markdown("## Model Probabilities")
                    probs_frame = pd.DataFrame()
                    if result.get("bilstm_probs") is not None:
                        probs_frame["BiLSTM"] = _normalize_probs_for_display(result.get("bilstm_probs"))
                    if result.get("bert_probs") is not None:
                        probs_frame["BERT"] = _normalize_probs_for_display(result.get("bert_probs"))
                    if probs_frame.empty:
                        st.info("No model probabilities available.")
                    else:
                        probs_frame.index = LABELS
                        for col_name in probs_frame.columns:
                            st.markdown(f"**{col_name}**")
                            for label, val in probs_frame[col_name].items():
                                st.progress(int(float(val) * 100), text=f"{label}: {val:.2f}")

    # --- HISTORY + ANALYTICS ---
    st.markdown("---")
    st.header("Prediction History & Analytics")

    try:
        df = load_history_dataframe()
        if df.empty:
            st.info("No prediction history available.")
        else:
            # Search history by text or label.
            search_col, download_col = st.columns([3, 1])
            query = search_col.text_input("Search history (text or label)")
            if query:
                mask = df.apply(lambda row: query.lower() in str(row.values).lower(), axis=1)
                df_filtered = df[mask]
            else:
                df_filtered = df

            download_col.download_button(
                "Download CSV",
                data=download_dataframe_as_csv(df_filtered),
                file_name="prediction_history.csv",
            )

            st.dataframe(df_filtered.sort_values(by="timestamp", ascending=False))

            # Analytics charts are wrapped in a try/except so one bad row cannot crash the app.
            a1, a2 = st.columns(2)
            with a1:
                st.subheader("Emotion Distribution")
                dist = df["final_prediction"].value_counts().reindex(LABELS).fillna(0)
                fig = px.bar(x=dist.index, y=dist.values, labels={"x": "Emotion", "y": "Count"}, title="Emotion Counts")
                st.plotly_chart(fig, use_container_width=True)

            with a2:
                st.subheader("Weekly Trends")
                df_week = df.set_index("timestamp").resample("W")["final_prediction"].value_counts().unstack(fill_value=0)
                if not df_week.empty:
                    fig2 = px.area(df_week, title="Weekly Emotion Trends")
                    st.plotly_chart(fig2, use_container_width=True)

            st.subheader("Pie Chart")
            fig3 = px.pie(names=dist.index, values=dist.values, title="Emotion Share")
            st.plotly_chart(fig3, use_container_width=True)
    except Exception as exc:
        logger.exception("Analytics failed while loading history.")
        st.warning(f"Analytics could not be loaded right now: {exc}")

    # --- MODEL EVALUATION COMPARISON ---
    st.markdown("---")
    st.header("Model Evaluation (BiLSTM vs BERT)")

    eval_data = _load_evaluation_comparison()
    if not eval_data.get("artifacts_present"):
        st.info("Run `python training/evaluate_models.py --model both` to generate evaluation artifacts.")
    else:
        compare_df = eval_data.get("compare_df")
        if compare_df is not None and not compare_df.empty:
            best_model = None
            try:
                if eval_data.get("compare_json") and eval_data["compare_json"].get("best_model"):
                    best_model = eval_data["compare_json"]["best_model"]
            except Exception:
                best_model = None

            display_df = compare_df.copy()
            display_df.columns = [str(col).strip().lower() for col in display_df.columns]
            if "model" not in display_df.columns:
                display_df = display_df.reset_index().rename(columns={"index": "model"})
            metric_cols = [col for col in ["accuracy", "precision", "recall", "f1"] if col in display_df.columns]
            if metric_cols:
                display_df = display_df[["model", *metric_cols]]

            if best_model:
                st.success(f"Best-performing model (by F1): {best_model}")

            st.subheader("Comparison Table")
            st.dataframe(display_df)

            st.subheader("Metrics")
            st.write(display_df.set_index("model")[metric_cols].round(4))
        else:
            st.warning("Comparison table not available.")

        # Confusion matrices
        c1, c2 = st.columns(2)
        cm_bilstm_path = eval_data.get("cm_bilstm_path")
        cm_bert_path = eval_data.get("cm_bert_path")

        with c1:
            st.subheader("BiLSTM Confusion Matrix")
            if cm_bilstm_path and os.path.exists(cm_bilstm_path):
                st.image(cm_bilstm_path, use_container_width=True)
            else:
                st.info("Confusion matrix image not found.")

        with c2:
            st.subheader("BERT Confusion Matrix")
            if cm_bert_path and os.path.exists(cm_bert_path):
                st.image(cm_bert_path, use_container_width=True)
            else:
                st.info("Confusion matrix image not found.")
